#spring.application.name=lerningAI
#
##spring.datasource.url=jdbc:mysql://localhost:3306/Learning_Resume
##spring.datasource.username=root
##spring.datasource.password=abhishek
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/learning_resume}
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASSWORD:abhishek}

spring.application.name=lerningAI

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Database Connection using Aiven details
# We add useSSL=true and trustServerCertificate=true because Aiven requires encrypted connections
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-15d3c89-abhishekrbmeena-7618.f.aivencloud.com:23799/defaultdb?useSSL=true&trustServerCertificate=true}
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_j9YKYe7Gh9Ws2bB1ues}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver





spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartplace.com@gmail.com
spring.mail.password=oxda xaoz awsy yxse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true