spring.application.name=lerningAI

#spring.datasource.url=jdbc:mysql://localhost:3306/Learning_Resume
#spring.datasource.username=root
#spring.datasource.password=abhishek

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/learning_resume}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:abhishek}